// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxfvgxevptagiksicupn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4ZnZneGV2cHRhZ2lrc2ljdXBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1Mjc1MzYsImV4cCI6MjA3MzEwMzUzNn0.qhfzjd5OgD9Gm_2HO4LKsUFOl10owh2x3p_PiSVh1qc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});